{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml .Values.service.annotations) . | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range .Values.defaultPorts }}
    - name: agent-{{ .name }}
      port: {{ .port }}
      {{- if hasKey . "protocol" }}
      protocol: {{ .protocol }}
      {{- end }}
      targetPort: {{ .port }}
    {{- end }}
    {{- range .Values.extraPorts }}
    - name: agent-{{ .name }}
      port: {{ .port }}
      {{- if hasKey . "protocol" }}
      protocol: {{ .protocol }}
      {{- end }}
      targetPort: {{ .port }}
    {{- end }}
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
{{- end }}
