{{- if and .Values.enabled .Values.configMap.create .Values.config.agentDeployment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (include "this.fullnameDeployment" .) .Values.configMap.nameDeployment }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "this.labelsDeployment" . | nindent 4 }}
data:
  agent.yaml: |
    {{- tpl .Values.config.agentDeployment . | nindent 4}}
{{- end }}
