apiVersion: v2
appVersion: 1.3.0
description: A Helm chart for guacamole
name: guacamole
version: 0.2.1-4
dependencies:
- name: mysql
  version: 1.6.9
  repository: https://helm.wso2.com
  condition: mysql.enabled
